version: "3"

services:
  backend:
    image: cosmtrek/air
    ports:
      - 1323:1323
    env_file:
      - .env
    working_dir: /work/backend
    volumes:
      - .:/work
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    depends_on:
      - rabbitmq
      - mysql

  video-processor:
    image: cosmtrek/air
    env_file:
      - .env
    working_dir: /work/video-processor
    volumes:
      - .:/work
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    depends_on:
      - rabbitmq
      - minio
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=pass
    ports:
      - 1234:80
    volumes:
      - phpmyadmin:/sessions

volumes:
  mysql:
  phpmyadmin:
