version: "3"

services:
  backend:
    image: cosmtrek/air
    working_dir: /work/backend
    volumes:
      - .:/work
    depends_on:
      - rabbitmq
      - mysql

  video-processor:
    image: cosmtrek/air
    working_dir: /work/video-processor
    volumes:
      - .:/work
    depends_on:
      - rabbitmq
      - minio
      - mysql

  rabbitmq:
    image: rabbitmq:3.9
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass

  minio:
    image: minio/minio:RELEASE.2022-03-14T18-25-24Z
    ports:
      - 9001:9001
    command: server /data --console-address :9001
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    volumes:
      - minio:/data

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - mysql:/var/lib/mysql

volumes:
  minio:
  mysql:
