version: "3"

services:
  backend:
    image: cosmtrek/air
    ports:
      - 1323:1323
    env_file:
      - .env
    working_dir: /work/backend
    volumes:
      - .:/work
    depends_on:
      - rabbitmq
      - mysql

  video-processor:
    image: cosmtrek/air
    env_file:
      - .env
    working_dir: /work/video-processor
    volumes:
      - .:/work
    depends_on:
      - rabbitmq
      - minio
      - mysql

  rabbitmq:
    image: rabbitmq:3.9
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass

  minio:
    image: minio/minio:RELEASE.2022-03-14T18-25-24Z
    ports:
      - 9001:9001
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=accesskey
      - MINIO_ROOT_PASSWORD=secretkey
    volumes:
      - minio:/data

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=pass
    ports:
      - 1234:80
    volumes:
      - phpmyadmin:/sessions

volumes:
  minio:
  mysql:
  phpmyadmin:
